version: "3"
services:
    palworld-server-tool:
        container_name: pst
        restart: always
        ports:
            - 8080:8080
        volumes:
            - /path/to/your/Pal/Saved/SaveGames/0/E8F71231A51246429C7CCCCD51320C22:/game
        environment:
            - WEB__PASSWORD="your password"
            - RCON__ADDRESS="172.17.0.1:25575"
            - RCON__PASSWORD="your password"
            - SAVE__PATH="/game/Level.sav"
            - SAVE__SYNC_INTERVAL=120
        image: jokerwho/palworld-server-tool:latest
